name = "sweepstake"
compatibility_date = "2026-05-11"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "sweepstake-db"
database_id = "f0ecb20d-cea1-4404-b9bc-34e9ae971808"

[vars]
FOOTBALL_API_KEY = "4c5d824cb4ed8c20d0241833fc2d9483"
